### ISSUE TITLE
Android Phonegap

### ISSUE THREAD

**Issue by julie78990** [andrastoth/WebCodeCam#10]
Hi András,
I'm trying to use your plugin in a phonegap project but I didn't manage to get it work. I tried on my Android phone (4.2.2) but when I use your demo and press on play, I get the following alert : "Sorry, he browser you are using doesn't support getUserMedia". 
Is there a way to make it work or is it just not compatible?
Thank you in advance,
Julie

**Comment by andrastoth** [comment]
Hi Julie,
This is depend on the OS (Phone) and the Browser. I think best choice is Chrome Latest (Currently).
My Blade V Android 4.2.2 with chrome working correctly .
I not used phonegap yet...

**Comment by julie78990** [comment]
Thank you for your fast answer.
According to this http://stackoverflow.com/questions/21069761/what-browser-engine-does-android-use-for-phonegap, Phoneap uses Webkit. So I will have to find a way to make it use Chrome...

**Comment by julie78990** [comment]
Hi,
Sorry, it's me again. I found a plugin to use Chrome webview but now I have another alert (cameraError). 
Error detected with the following parameters :
constraintName:
message:
name:DevicesNotFoundError
Any idea?

**Comment by julie78990** [comment]
Hi,
Sorry, it's me again. I have found a plugin using Chrome webview, I don't have any error message anymore but nothing happens when I press play and I cannot select a camera. 
Any idea?
