### ISSUE TITLE
How can i use in phone, it is working fine but open front camera can you please specify how can i set it to open back camera, is their any option for primary camera and secoundry camera?

### ISSUE THREAD

**Issue by prashantidealittechno** [andrastoth/WebCodeCam#11]

**Comment by prashantidealittechno** [comment]
i got the option before play button to select the camera can we make it set default with back camera with some code or js settings? i want to open only back camera(primary camera) as default camera?

**Comment by andrastoth** [comment]
Hello,
Optimal working depend on OS (version) and browser. Please try latest chrome.
On my blade-v working correctly (android 4.2 , chrome).
If you see select-menu on my demo page then this function working on your phone.
initialization example:

$('select#cameraId').children('option').eq(x).val()
x - index of cam.
 - main.js - 
decoder.WebCodeCam({
                videoSource: {
                    id: $('select#cameraId').children('option').eq(1).val(),
                    maxWidth: 640,
                    maxHeight: 480
                },
              .......
});

.......
    function init() {
        $(videoSelect).change(function(event) {
            if (typeof decoder.data().plugin_WebCodeCam !== "undefined") {
                decoder.data().plugin_WebCodeCam.options.videoSource.id = $(this).val();
                decoder.data().plugin_WebCodeCam.cameraStop();
                decoder.data().plugin_WebCodeCam.cameraPlay(false);
                Log('videoSelectChange(id)', $(this).val());
            } else {
                Log('videoSelectChange(id)', 'false');
            }
        });
        pl.click(); /* start immediately
    }

I hope this is help for you.
