### ISSUE TITLE
How i do to get the back camera from mobile device in a webview?

### ISSUE THREAD

**Issue by JohanMa4** [andrastoth/WebCodeCam#13]
Hi @andrastoth, i have a little problem by selecting the back camera from the mobile device, is there any way to get the back camera from the mobile device?

I need to select the back camera because is the most easily and friendly way for user to scan qrcodes.

Regards :)

**Comment by andrastoth** [comment]
Hello,

Try this:

 /* Select environment camera if available, without visible select menu*/
    decoder.buildSelectMenu(document.createElement('select'), 'environment|back').init().play();   

Regards

**Comment by JohanMa4** [comment]
Thanks man, i will test this
