### ISSUE TITLE
Back camera not available

### ISSUE THREAD

**Issue by osotorrio** [andrastoth/WebCodeCam#2]
Hi Tóth,

I would like to use your library but I could not get it working with the back camera. I have tried to hardcode the sourceId in the initCamera function, for instance:

if (navigator.getUserMedia) {                           
navigator.getUserMedia({               
video: {                                     
       optional: [{ sourceId: "4cd487e...etc...f1a5ad9fc" }],         
       mandatory: {
                   maxWidth: this.options.videoSource.maxWidth, 
                   maxHeight: this.options.videoSource.maxHeight
                  }                   
},                    
audio: false              
}

Some specifications
Operating system: Android 4.4.4; Nexus 5
Chrome 40

I hope you could help me.

In advance thanks for your effort.

**Comment by andrastoth** [comment]
Hi Óscar,

So, your solution is correct, but only working on android and other mobile
devices.
I added a new version with selectable videosource.
If i know correctly,
sourceInfo.facing on personal computer (windows) always empty.string.
Please check out a new version from github.
Demo page also update.

Regards
Tóth András

2015-02-13 15:10 GMT+01:00 Óscar Sotorrío <notifications@github.com>:

**Comment by osotorrio** [comment]
Hi Tóth, 

Your solution is much better than mine :+1: 

Thank you very much for the fast update!!
