### ISSUE TITLE
Not working on iOS with bowser

### ISSUE THREAD

**Issue by Mattze96** [andrastoth/WebCodeCam#5]
Hello, i use the browser called bowser to support the getusermedia function on ios devices.

For some reason no video is displayed when i click play and even no selection-options for the front and back camera. The dropdown box appears, but has no entries.

**Comment by andrastoth** [comment]
Hello,
Please look at these pages.
I know it can be reached only partial operation.

Android system also created a similar problem,
with system and browser context.

http://caniuse.com/#feat=stream
http://mobilehtml5.org/
