### ISSUE TITLE
Memory problem

### ISSUE THREAD

**Issue by efkan** [andrastoth/WebCodeCam#6]
First of all, the module seems very useful. Thank you. I've tried. 
However, it has some memory problems. When a browser is opened, used memory increases severely.

I tried the following line in the `function getBase64Image(img)` function. I guess it benefits a bit.

    /* MEMORY RECOVER */ setTimeout(function(){ canvas = undefined; dataURL = undefined }, 500)

**Comment by andrastoth** [comment]
Hi, Thank you.

So, this function (getBase64Image)  is not used. 
Used memory size about 500 000K. Standby about 65 000K, Video Stream about 100 000K, two decoding algorithm about 150 000K  per algorithm.
I'm not sure that I can significantly reduce the memory consumption.
I'll see what can be done.
