### ISSUE TITLE
no callback for errors?

### ISSUE THREAD

**Issue by cisnerosebastian** [andrastoth/WebCodeCam#7]
is there a way to have a calback for errors like
"Something went wrong"
"Sorry the browser you are using doesn't support GetUserMedia"

**Comment by andrastoth** [comment]
please tell me exactly what you mean

**Comment by cisnerosebastian** [comment]
for example, if cam is not allowed by user, you will get an js alert error "Something went wrong".

instead of that, is there a way to have a callback function , when error is found, it can fire callback function. Just like the "resultFunction" , but when there is an error.

**Comment by andrastoth** [comment]
I understand, This is a good idea. I will implement this in the next version.

**Comment by cisnerosebastian** [comment]
great. By the way, great plugin so far.

**Comment by andrastoth** [comment]
Added in Version 1.0.0
