### ISSUE TITLE
Openning frontal cam

### ISSUE THREAD

**Issue by karlmendes** [andrastoth/WebCodeCam#8]
Hi @andrastoth  by default the js openning the frontal cam of smart, has a conf to force open the rear cam ??

**Comment by karlmendes** [comment]
Update:
When i import the main.js has be the error like
TypeError: document.querySelector(...) is null .... main.js:157

**Comment by andrastoth** [comment]
Hello


So, first question is which device , operation system and browser you use.

Please try this modification:

    var videoSelect = document.getElementById('cameraId');

    function gotSources(sourceInfos) {
        for (var i = 0; i !== sourceInfos.length; ++i) {
            var sourceInfo = sourceInfos[i];
            var option = document.createElement('option');
            option.value = sourceInfo.id;
            if (sourceInfo.kind === 'video') {
                var face = sourceInfo.facing == '' ? 'unknown' :
sourceInfo.facing;
                option.text = sourceInfo.label || 'camera ' +
(videoSelect.length + 1) + ' (facing: ' + face + ')';
                videoSelect.appendChild(option);
            }
        }
        init();
    }
    if (typeof MediaStreamTrack.getSources !== 'undefined') {
        MediaStreamTrack.getSources(gotSources);
    } else {
        document.getElementById('cameraId').remove();
    }

    function init() {
        $(videoSelect).change(function(event) {
            if (typeof decoder.data().plugin_WebCodeCam !== "undefined") {
                decoder.data().plugin_WebCodeCam.options.videoSource.id =
$(this).val();
                decoder.data().plugin_WebCodeCam.cameraStop();
                decoder.data().plugin_WebCodeCam.cameraPlay(false);
            }
        });
    };

Tested on:

PC (Chrome, Firefox)
Mobile: Blade V (Android 4.1.2, Chrome)


2015-05-21 20:39 GMT+02:00 karlmendes <notifications@github.com>:

**Comment by andrastoth** [comment]
I am inserting the changes to its website.

http://atandrastoth.co.uk/main/pages/plugins/codereader/


2015-05-22 7:16 GMT+02:00 Andras Toth <atandrastoth@gmail.com>:

**Comment by karlmendes** [comment]
Thx for answer i'll try apply the code..... I used a LG G2 with Chrome, the cam open and the qrcode reader read perfect, only the issue is openned the frontal cam...

**Comment by karlmendes** [comment]
Only the frontal cam :(.

I tryng click a button and open the rear cam, i dont know if only parameter take this or i need modify the source code, can u help pls ?

**Comment by karlmendes** [comment]
In the qrcanvas appear the frontcam and in cameraId dont list anything

**Comment by andrastoth** [comment]
Hi
I added a logger function to my demo page.
Please navigate my demopage.
Try some options, stop, stopall, play, scan, reload page.
Send me the time, when you are testing .
I will analyzing the log file and send to you.


2015-05-25 14:58 GMT+02:00 karlmendes <notifications@github.com>:

**Comment by karlmendes** [comment]
Hi @andrastoth I try test the plugin on anothers smartphones (Moto G, Samsung Win Duos) but all show only front cam.

**Comment by karlmendes** [comment]
Hi @andrastoth the logger are active yet ? I'm beggin another project, but now i'll fisish this.... Have u try use the lib in windows edge ? Thx a lot !

**Comment by karlmendes** [comment]
If i used ur code example, all cameras are avaiable, but open the front first, but if show all cameras, perfect..

**Comment by karlmendes** [comment]
Hi @andrastoth, i fix the code to show the cams... apparently is permission, i call the function inside a dialog, dont listen anything in cameraId, now i fix this..... My problem now, is in order the select of the found cams, environmet first, before the face cam...

**Comment by andrastoth** [comment]
Hello,
Sorry for my late reply, but I was on holiday.
Please send me your modified code, I will check this out.
And it is working fine for me, I Will implement to the project.
Thank you
András

2015-07-21 20:08 GMT+02:00 karlmendes <notifications@github.com>:

**Comment by karlmendes** [comment]
$('#bt_qrCode').click(function(){
          if ($('#cameraId').length > 0){
            $('#QR-Code').slideToggle("slow");
            if ($('#cameraId').length == 1){
              $('#play').remove();
              $('#stop').remove();
              $('#cameraId').css("opacity",0);

              $('#qr-canvas').WebCodeCam({
                ReadQRCode: true, // false or true
                ReadBarecode: true, // false or true
                width: 320,
                height: 240,
                videoSource: {  
                  id: true,      //default Videosource
                  maxWidth: 320, //max Videosource resolution width
                  maxHeight: 240 //max Videosource resolution height
                },
                flipVertical: false,  // false or true
                flipHorizontal: false,  // false or true
                zoom: -1, // if zoom = -1, auto zoom for optimal resolution else int
                beep: "js/beep.mp3", // string, audio file location
                autoBrightnessValue: false, // functional when value autoBrightnessValue is int
                brightness: 0, // int 
                grayScale: false, // false or true
                contrast: 0, // int 
                threshold: 0, // int 
                sharpness: [], //or matrix, example for sharpness ->  [0, -1, 0, -1, 5, -1, 0, -1, 0]
                resultFunction: function(resText, lastImageSrc) {
                  alert(resText);
                },
                getUserMediaError: function() {
                  alert("Not possible");
                },
                cameraError: function(error) {
                  alert("Not possible");
                }
              });
            }
          }else
            libcaptive.alerta("question_retorno", "Not possible);
        });

**Comment by karlmendes** [comment]
In desktop chrome, if i alert in cameraId,lenght, the result is 1.... but dont have any cams, its right ? If found any cam the result is > 1 ?

thx a lot...

**Comment by karlmendes** [comment]
I take the val() of cameraId, and if not null open the function.

**Comment by andrastoth** [comment]
Hello

$('#cameraId').length allways 1 because this is elements count with
selected by '#cameraId'.
the correct is $('#cameraId').children().length or val() != null.

2015-07-22 16:18 GMT+02:00 karlmendes <notifications@github.com>:

**Comment by karlmendes** [comment]
Right, thx.... The method of i call the stop camera before take the code, is right ?

**Comment by andrastoth** [comment]
decoder.data().plugin_WebCodeCam.cameraStop(); = pause video and decoder
algorythms

decoder.data().plugin_WebCodeCam.cameraStopAll(); = delete streams and pause
video and decoder algorythms

2015-07-22 18:20 GMT+02:00 karlmendes <notifications@github.com>:

**Comment by karlmendes** [comment]
Little details but works perfectly, one thing, i need pause cam if i need change the cam ?

**Comment by andrastoth** [comment]
Hello

decoder.data().plugin_WebCodeCam.cameraStop(); = pause video and decoder
algorythms

decoder.data().plugin_WebCodeCam.cameraStopAll(); = delete streams and pause
video and decoder algorythms



2015-07-22 20:29 GMT+02:00 Karl <notifications@github.com>:
