### ISSUE TITLE
QR code too complex

### ISSUE THREAD

**Issue by aurel27** [andrastoth/WebCodeCam#9]
Hi @andrastoth ,

I can't read this qr code, can't it is too complex?

the picture capture by webcam is too blur ? 

my qr code 

https://drive.google.com/file/d/0B-pGEYLoJLSiMXJSdFhqSWFsUnVtUFhQMVRGYzNZU2lDeDJR/view?usp=sharing

Thanks for help.
Best regards.

**Comment by andrastoth** [comment]
Hello

I tried and it works.

Some help for you:

Settings for screenshot 1:

width: 320,
height: 240,
videoSource: {
id: true,
maxWidth: 1280,
maxHeight: 720
},
Settings for screenshot 2:

width: 640,
height: 480,
videoSource: {
id: true,
maxWidth: 1280,
maxHeight: 720
},

The focus is very important!

My camera is focusable manually.

I hope this will help you.

Best regards.
András


2015-06-01 13:24 GMT+02:00 aurel27 <notifications@github.com>:

**Comment by aurel27** [comment]
thanks  @andrastoth  , Great plugin.

I modify settings for screenshot but my camera is not focusable manually. i will try with another.


Can I read datamatrix or not ??: 

https://drive.google.com/file/d/0B-pGEYLoJLSiTjNucDBkSk92RFZEZ3B4VjNFdk92Z3hmUGhR/view?usp=sharing

**Comment by andrastoth** [comment]
My plugin is not supported Data Matrix.

2015-06-01 15:22 GMT+02:00 aurel27 <notifications@github.com>:

**Comment by karlmendes** [comment]
Hi @andrastoth  the logger are active yet ? I'm beggin another project, but now i'll fisish this.... Have u try use the lib in windows edge ? Thx a lot !
